
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        env:
          VITE_SUPABASE_URL: "https://nmioehwnmclzujbcyliz.supabase.co"
          VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5taW9laHdubWNsenVqYmN5bGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDMzMzYsImV4cCI6MjA3NzcxOTMzNn0.AXLCRlR1j2LL1hvgI0N6hC_SxzQcrdUMihDKdSJCWqQ"
          VITE_SUPABASE_PROJECT_ID: "nmioehwnmclzujbcyliz"
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
